<?php if($this->getProduct()): ?>
<script>
	(function() {
		var tc_goodvidio_div_main = document.querySelectorAll("<?= $this->getSelector(); ?>")[0];
		if (typeof tc_goodvidio_div_main != "undefined" && tc_goodvidio_div_main != null) {
	    var goodvidio_div1 = document.createElement("div");
	    goodvidio_div1.id = "goodvidio-product-videos";

			<?php if($this->getPosition() === "before"): ?>
	    	tc_goodvidio_div_main.parentNode.insertBefore(goodvidio_div1, tc_goodvidio_div_main);
			<?php elseif($this->getPosition() === "after"): ?>
				tc_goodvidio_div_main.parentNode.insertBefore(goodvidio_div1, tc_goodvidio_div_main.nextSibling);
			<?php endif; ?>

	    var goodvidio_div2 = document.createElement("div");
	    goodvidio_div2.id = "tc_div_325_1";
	    goodvidio_div2.className = "goodvidio-product-track";
	    goodvidio_div2.setAttribute("data-goodvidio-product-id", <?= $this->getProduct()->getSku(); ?>);
	    goodvidio_div1.appendChild(goodvidio_div2);
		}
	})();
</script>
<?php endif; ?>
